services:
  - type: web
    name: djangocrud
    env: python
    region: ohio
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn djangocrud.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER
        value: "true"
