# Generated by Django 6.0.1 on 2026-01-25 01:09

import django.db.models.deletion
import django_countries.fields
import portafolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('descripcionperfil', models.TextField(blank=True, max_length=500, null=True)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', django_countries.fields.CountryField(default='EC', max_length=2)),
                ('lugarnacimiento', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField(validators=[portafolio.models.validar_fecha_nacimiento])),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión Libre', 'Unión Libre')], max_length=50)),
                ('licenciaconducir', models.CharField(choices=[('No', 'No posee'), ('Tipo A', 'Tipo A'), ('Tipo B', 'Tipo B'), ('Tipo C', 'Tipo C'), ('Tipo D', 'Tipo D'), ('Tipo E', 'Tipo E')], max_length=20)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('direcciondomiciliaria', models.CharField(max_length=100)),
                ('sitioweb', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=150)),
                ('totalhoras', models.IntegerField()),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('descripcioncurso', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=20, null=True)),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=254, null=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_cursos/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencilaboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombrempresa', models.CharField(max_length=100)),
                ('lugarempresa', models.CharField(max_length=100)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('emailempresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.URLField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=20, null=True)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.TextField(blank=True, null=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_laborales/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=150)),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=150)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=200)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=20, null=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_reconocimientos/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='garage/')),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], default='Bueno', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.datospersonales')),
            ],
        ),
    ]
