# Generated by Django 6.0.1 on 2026-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='actitudes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='aptitudes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
