# Generated by Django 6.0.1 on 2026-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_datospersonales_actitudes_datospersonales_aptitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: 593987654321 (Sin el +)', max_length=15, null=True),
        ),
    ]
