# Generated by Django 6.0.1 on 2026-01-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_datospersonales_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: 593987654321', max_length=15, null=True),
        ),
    ]
