# Generated by Django 6.0.1 on 2026-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_remove_datospersonales_whatsapp_ventagarage_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
