# Generated by Django 6.0.1 on 2026-02-02 16:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados_cursos/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados_laborales/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados_reconocimientos/'),
        ),
    ]
